{{- if .Values.ingress.enabled -}}
{{- $root := . -}}
{{- $fullName := include "locust.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "locust.fullname" . }}
  labels:
    app: locust
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $root.Values.pathBase }}
            backend:
              serviceName: {{ template "locust.master-ingress-svc" $root }}
              servicePort: master-web
  {{- end }}
{{- end }}