helm delete --purge eshop-apigwmm
helm delete --purge eshop-apigwms
helm delete --purge eshop-apigwwm
helm delete --purge eshop-apigwws
helm delete --purge eshop-basket-api
helm delete --purge eshop-basket-data
helm delete --purge eshop-catalog-api
helm delete --purge eshop-identity-api
helm delete --purge eshop-keystore-data
helm delete --purge eshop-locations-api
helm delete --purge eshop-marketing-api
helm delete --purge eshop-mobileshoppingagg
helm delete --purge eshop-nosql-data
helm delete --purge eshop-ordering-api
helm delete --purge eshop-ordering-backgroundtasks
helm delete --purge eshop-ordering-signalrhub
helm delete --purge eshop-payment-api
helm delete --purge eshop-rabbitmq